baseurl:          /blog
markdown:         rdiscount
pygments:         true
permalink:        pretty
exclude:
- ".gitignore"
- "CNAME"
- "DOCS-LICENSE"
- "LICENSE"
- "README.md"

# 自定义全局变量
version:          1.0.0