# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
baseurl:          /blog
exclude:
- ".gitignore"
- "CNAME"
- "DOCS-LICENSE"
- "LICENSE"
- "README.md"

# Custom vars
jquery_js:        https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js
bs_js:            https://raw.github.com/twbs/bootstrap/master/dist/js/bootstrap.min.js
bs_css:           https://raw.github.com/twbs/bootstrap/master/dist/css/bootstrap.min.css

current_version:  3.0.3
repo:             https://github.com/twbs/bootstrap

download_source:  https://github.com/twbs/bootstrap/archive/v3.0.3.zip
download_dist:    https://github.com/twbs/bootstrap/releases/download/v3.0.3/bootstrap-3.0.3-dist.zip

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com
sass_repo:        https://github.com/twbs/bootstrap-sass

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js