baseurl:          /blog
markdown:         rdiscount
pygments:         true
permalink:        pretty
paginate:         6

# 自定义全局变量
name:             Jnoee Blog
appid:            cyqWoqAdU
conf:             prod_1458c6647dbf7cca56dff7bfe0576ebb