markdown:         rdiscount
pygments:         true
permalink:        pretty
paginate:         6

name:             Jnoee Blog
url:              http://jnoee.github.io
ctx:              /blog
duoshuo:
  domain:         jnoee